var _audio___data___subject_8java =
[
    [ "com.springproject.dockerspring.Repository.SubjectEnum.Audio_Data_Subject", "enumcom_1_1springproject_1_1dockerspring_1_1_repository_1_1_subject_enum_1_1_audio___data___subject.html", "enumcom_1_1springproject_1_1dockerspring_1_1_repository_1_1_subject_enum_1_1_audio___data___subject" ]
];