var _audio___data___repo_8java =
[
    [ "com.springproject.dockerspring.Repository.NormalRepo.Audio_Data_Repo", "interfacecom_1_1springproject_1_1dockerspring_1_1_repository_1_1_normal_repo_1_1_audio___data___repo.html", "interfacecom_1_1springproject_1_1dockerspring_1_1_repository_1_1_normal_repo_1_1_audio___data___repo" ]
];