var _audio___data___enum___test_8java =
[
    [ "com.springproject.dockerspring.SingleTests.CommonEnum.NormalEnum.Audio_Data_Enum_Test", "classcom_1_1springproject_1_1dockerspring_1_1_single_tests_1_1_common_enum_1_1_normal_enum_1_1_audio___data___enum___test.html", "classcom_1_1springproject_1_1dockerspring_1_1_single_tests_1_1_common_enum_1_1_normal_enum_1_1_audio___data___enum___test" ]
];