var _audio___data___samba_impl_8java =
[
    [ "com.springproject.dockerspring.FileIO.SambaProcess.Audio_Data_SambaImpl", "classcom_1_1springproject_1_1dockerspring_1_1_file_i_o_1_1_samba_process_1_1_audio___data___samba_impl.html", "classcom_1_1springproject_1_1dockerspring_1_1_file_i_o_1_1_samba_process_1_1_audio___data___samba_impl" ]
];