var _audio___data___service_impl_8java =
[
    [ "com.springproject.dockerspring.Service.ServiceImpl.Audio_Data_ServiceImpl", "classcom_1_1springproject_1_1dockerspring_1_1_service_1_1_service_impl_1_1_audio___data___service_impl.html", "classcom_1_1springproject_1_1dockerspring_1_1_service_1_1_service_impl_1_1_audio___data___service_impl" ]
];