var _audio___data___history_8java =
[
    [ "com.springproject.dockerspring.Entity.HistoryEntity.Audio_Data_History", "classcom_1_1springproject_1_1dockerspring_1_1_entity_1_1_history_entity_1_1_audio___data___history.html", "classcom_1_1springproject_1_1dockerspring_1_1_entity_1_1_history_entity_1_1_audio___data___history" ]
];