var _authority___kinds___enum___test_8java =
[
    [ "com.springproject.dockerspring.SingleTests.CommonEnum.UtilEnum.Authority_Kinds_Enum_Test", "classcom_1_1springproject_1_1dockerspring_1_1_single_tests_1_1_common_enum_1_1_util_enum_1_1_authority___kinds___enum___test.html", "classcom_1_1springproject_1_1dockerspring_1_1_single_tests_1_1_common_enum_1_1_util_enum_1_1_authority___kinds___enum___test" ]
];