var _authority___kinds___enum_8java =
[
    [ "com.springproject.dockerspring.CommonEnum.UtilEnum.Authority_Kinds_Enum", "enumcom_1_1springproject_1_1dockerspring_1_1_common_enum_1_1_util_enum_1_1_authority___kinds___enum.html", "enumcom_1_1springproject_1_1dockerspring_1_1_common_enum_1_1_util_enum_1_1_authority___kinds___enum" ]
];