var _auth_connect_check_8java =
[
    [ "com.springproject.dockerspring.Form.OriginalAnno.AuthConnectCheck", "interfacecom_1_1springproject_1_1dockerspring_1_1_form_1_1_original_anno_1_1_auth_connect_check.html", "interfacecom_1_1springproject_1_1dockerspring_1_1_form_1_1_original_anno_1_1_auth_connect_check" ],
    [ "com.springproject.dockerspring.Form.OriginalAnno.AuthConnectCheck.List", "interfacecom_1_1springproject_1_1dockerspring_1_1_form_1_1_original_anno_1_1_auth_connect_check_1_1_list.html", "interfacecom_1_1springproject_1_1dockerspring_1_1_form_1_1_original_anno_1_1_auth_connect_check_1_1_list" ]
];