var _common_utils_service_8java =
[
    [ "com.springproject.dockerspring.Service.CommonMethods.CommonUtilsService", "classcom_1_1springproject_1_1dockerspring_1_1_service_1_1_common_methods_1_1_common_utils_service.html", "classcom_1_1springproject_1_1dockerspring_1_1_service_1_1_common_methods_1_1_common_utils_service" ],
    [ "com.springproject.dockerspring.Service.CommonMethods.CommonUtilsService.BlobEntityFunction< E >", "interfacecom_1_1springproject_1_1dockerspring_1_1_service_1_1_common_methods_1_1_common_utils_service_1_1_blob_entity_function.html", "interfacecom_1_1springproject_1_1dockerspring_1_1_service_1_1_common_methods_1_1_common_utils_service_1_1_blob_entity_function" ]
];