var _db_action_exception_8java =
[
    [ "com.springproject.dockerspring.Service.OriginalException.DbActionException", "classcom_1_1springproject_1_1dockerspring_1_1_service_1_1_original_exception_1_1_db_action_exception.html", "classcom_1_1springproject_1_1dockerspring_1_1_service_1_1_original_exception_1_1_db_action_exception" ]
];