var _entity___make_map___test_8java =
[
    [ "com.springproject.dockerspring.SingleTests.Entity.TestInterface.Entity_MakeMap_Test", "interfacecom_1_1springproject_1_1dockerspring_1_1_single_tests_1_1_entity_1_1_test_interface_1_1_entity___make_map___test.html", "interfacecom_1_1springproject_1_1dockerspring_1_1_single_tests_1_1_entity_1_1_test_interface_1_1_entity___make_map___test" ]
];