var _facility___photo___repo_8java =
[
    [ "com.springproject.dockerspring.Repository.NormalRepo.Facility_Photo_Repo", "interfacecom_1_1springproject_1_1dockerspring_1_1_repository_1_1_normal_repo_1_1_facility___photo___repo.html", "interfacecom_1_1springproject_1_1dockerspring_1_1_repository_1_1_normal_repo_1_1_facility___photo___repo" ]
];