var _member___info___history___repo_8java =
[
    [ "com.springproject.dockerspring.Repository.HistoryRepo.Member_Info_History_Repo", "interfacecom_1_1springproject_1_1dockerspring_1_1_repository_1_1_history_repo_1_1_member___info___history___repo.html", "interfacecom_1_1springproject_1_1dockerspring_1_1_repository_1_1_history_repo_1_1_member___info___history___repo" ]
];