var _member___info___history_8java =
[
    [ "com.springproject.dockerspring.Entity.HistoryEntity.Member_Info_History", "classcom_1_1springproject_1_1dockerspring_1_1_entity_1_1_history_entity_1_1_member___info___history.html", "classcom_1_1springproject_1_1dockerspring_1_1_entity_1_1_history_entity_1_1_member___info___history" ]
];