var _musical___score___repo_8java =
[
    [ "com.springproject.dockerspring.Repository.NormalRepo.Musical_Score_Repo", "interfacecom_1_1springproject_1_1dockerspring_1_1_repository_1_1_normal_repo_1_1_musical___score___repo.html", "interfacecom_1_1springproject_1_1dockerspring_1_1_repository_1_1_normal_repo_1_1_musical___score___repo" ]
];