var _normal___enum___test_8java =
[
    [ "com.springproject.dockerspring.SingleTests.CommonEnum.Normal_Enum_Test", "interfacecom_1_1springproject_1_1dockerspring_1_1_single_tests_1_1_common_enum_1_1_normal___enum___test.html", "interfacecom_1_1springproject_1_1dockerspring_1_1_single_tests_1_1_common_enum_1_1_normal___enum___test" ]
];