var _score___pdf___subject_8java =
[
    [ "com.springproject.dockerspring.Repository.SubjectEnum.Score_Pdf_Subject", "enumcom_1_1springproject_1_1dockerspring_1_1_repository_1_1_subject_enum_1_1_score___pdf___subject.html", "enumcom_1_1springproject_1_1dockerspring_1_1_repository_1_1_subject_enum_1_1_score___pdf___subject" ]
];