var _single_tests_2_entity_2_test_interface_2_entity___hist_input___test_8java =
[
    [ "com.springproject.dockerspring.SingleTests.Entity.TestInterface.Entity_HistInput_Test", "interfacecom_1_1springproject_1_1dockerspring_1_1_single_tests_1_1_entity_1_1_test_interface_1_1_entity___hist_input___test.html", "interfacecom_1_1springproject_1_1dockerspring_1_1_single_tests_1_1_entity_1_1_test_interface_1_1_entity___hist_input___test" ]
];