var _system___user___subject_8java =
[
    [ "com.springproject.dockerspring.Repository.SubjectEnum.System_User_Subject", "enumcom_1_1springproject_1_1dockerspring_1_1_repository_1_1_subject_enum_1_1_system___user___subject.html", "enumcom_1_1springproject_1_1dockerspring_1_1_repository_1_1_subject_enum_1_1_system___user___subject" ]
];