var _system___user___repo_8java =
[
    [ "com.springproject.dockerspring.Repository.NormalRepo.System_User_Repo", "interfacecom_1_1springproject_1_1dockerspring_1_1_repository_1_1_normal_repo_1_1_system___user___repo.html", "interfacecom_1_1springproject_1_1dockerspring_1_1_repository_1_1_normal_repo_1_1_system___user___repo" ]
];