var _test_data_source_8java =
[
    [ "com.springproject.dockerspring.CommonTestCaseMaker.Configure.TestDataSource", "classcom_1_1springproject_1_1dockerspring_1_1_common_test_case_maker_1_1_configure_1_1_test_data_source.html", "classcom_1_1springproject_1_1dockerspring_1_1_common_test_case_maker_1_1_configure_1_1_test_data_source" ]
];