var _usage___authority___subject_8java =
[
    [ "com.springproject.dockerspring.Repository.SubjectEnum.Usage_Authority_Subject", "enumcom_1_1springproject_1_1dockerspring_1_1_repository_1_1_subject_enum_1_1_usage___authority___subject.html", "enumcom_1_1springproject_1_1dockerspring_1_1_repository_1_1_subject_enum_1_1_usage___authority___subject" ]
];