# /** 
#  **************************************************************************************
#  * @file application.yml
#  * 
#  * @brief このシステム全体の設定の定義を行う、環境変数などのファイルである。
#  * 
#  * @details 
#  * - なおコメントに関しては、Javaファイルのコメントと統一し、Doxygen&Javadocの書式で記述する。
#  * だが、YMLファイルはドキュメントコンパイルの対象外の為、あくまで見た目の統一である。
#  **************************************************************************************
#  */











# /** 
#  **************************************************************************************
#  * @var spring
#  * 
#  * @brief SpringBootの主要な設定
#  * 
#  * @details 
#  * -# datasource
#  *    - データベース接続先URL
#  *    - 接続時のユーザー名
#  *    - 接続時のパスワード
#  *    - データベースドライバー名
#  * -# servlet
#  *    - 一個当たりのマルチパートファイルの許容データ量
#  *    - 一回のリクエスト当たりの許容データ量
#  *    - なお、どちらも許容値は[220MB]までとする。
#  **************************************************************************************
#  */
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/spring_schema
    username: spring_user
    password: spring_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 230686720
      max-request-size: 230686720







# /** 
#  **************************************************************************************
#  * @var logging
#  * 
#  * @brief システムのログ設定
#  * 
#  * @details 
#  * -# file
#  *    - ログファイル保存先のファイルパス
#  *    - 未圧縮で運用するログファイルの最大データ量
#  *    - 制限量を上回った場合、GZIP形式の圧縮ファイルとしてアーカイブされる
#  **************************************************************************************
#  */
logging:
  file:
    name: "LogFile/common-log-file.log"
    max-size: 1000000



# /** 
#  **************************************************************************************
#  * @var blob-limit
#  * 
#  * @brief このシステムで受け付けるバイナリデータの制限値
#  * 
#  * @details 
#  * -# バイナリデータではない通常データリストのリクエスト一回当たりの受付可能数
#  * -# 画像データリストのリクエスト一回当たりの受付可能数
#  * -# 音声データリストのリクエスト一回当たりの受付可能数
#  * -# PDFデータリストのリクエスト一回当たりの受付可能数
#  * -# 画像データの受付可能なファイルデータ量
#  * -# 音声データの受付可能なファイルデータ量
#  * -# PDFデータの受付可能なファイルデータ量
#  * -# CSVデータの受付可能なファイルデータ量
#  * -# ZIPデータの受付可能なファイルデータ量
#  **************************************************************************************
#  */
blob-limit:
  normal-list-size: 5
  photo-list-size: 5
  audio-list-size: 5
  pdf-list-size: 5
  photo-limit: 512000
  audio-limit: 209715200
  pdf-limit: 20971520
  csv-limit: 1048576
  zip-limit: 209715200
  


# /** 
#  **************************************************************************************
#  * @var data-limit
#  * 
#  * @brief データ検索時などの最大出力検索数や、システム上に保存できるバイナリデータの最大数など
#  * 
#  * @details 
#  * -# 一回の検索当たりの出力する最大の検索結果数
#  * -# このシステムが出力できる最大の検索結果数
#  * -# CSVファイルの受付時にエラーになった座標の出力可能最大数
#  * -# このシステムに保存可能な、管理番号一つ当たりの画像データの数量
#  * -# このシステムに保存可能な、管理番号一つ当たりの音声データの数量
#  * -# このシステムに保存可能な、管理番号一つ当たりのPDFデータの数量
#  **************************************************************************************
#  */
data-limit:
  offset: 50
  max: 500
  csv-error-list-limit: 50
  photo-save-limit: 50
  audio-save-limit: 10
  pdf-save-limit: 20



# /** 
#  **************************************************************************************
#  * @var samba
#  * 
#  * @brief ファイルサーバーへの接続時に用いるデータソース
#  * 
#  * @details 
#  * -# 接続先のファイルサーバーのURL
#  * -# 接続時のユーザー名
#  * -# 接続時のパスワード
#  * -# このシステムが対応可能なファイルサーバーのバージョンの最小値
#  * -# このシステムが対応可能なファイルサーバーのバージョンの最大値
#  * -# 接続や読み取りが遅かった際のタイムアウト時間。[30秒]とする。
#  **************************************************************************************
#  */
samba:
  url: smb://samba:139/filesystem
  username: spring_user
  password: spring_pass
  min-ver: SMB210
  max-ver: SMB300
  timeout: 30000



# /** 
#  **************************************************************************************
#  * @var jwt_token
#  * 
#  * @brief セキュリティで用いるJWTトークンの設定
#  * 
#  * @details 
#  * -# トークンの有効期間。[3分]とする。
#  **************************************************************************************
#  */
jwt_token:
  expiration-time: 180000



# /** 
#  **************************************************************************************
#  * @var output-filename
#  * 
#  * @brief CSVやZIPを出力する際の機能別のファイル名の指定
#  * 
#  * @details 
#  * -# 団員管理機能でのCSV出力時のファイル名
#  * -# 団員管理機能でのPDF出力時のファイル名
#  * -# 設備管理機能でのCSV出力時のファイル名
#  * -# 設備管理機能でのPDF出力時のファイル名
#  * -# 設備管理機能でのZIP出力時のファイル名
#  * -# 楽譜管理機能でのCSV出力時のファイル名
#  * -# 楽譜管理機能でのPDF出力時のファイル名
#  * -# 楽譜管理機能でのZIP出力時のファイル名
#  * -# 音源管理機能でのCSV出力時のファイル名
#  * -# 音源管理機能でのPDF出力時のファイル名
#  * -# 音源管理機能でのZIP出力時のファイル名
#  **************************************************************************************
#  */
output-filename:
  member-info-csv: 団員情報リスト
  member-info-pdf: 団員情報台帳
  facility-csv: 設備情報リスト
  facility-pdf: 設備情報台帳
  facility-zip: 設備写真
  musical-score-csv: 楽譜情報リスト
  musical-score-pdf: 楽譜情報台帳
  musical-score-zip: 楽譜データ
  sound-source-csv: 音源情報リスト
  sound-source-pdf: 音源情報台帳
  sound-source-zip: 音源データ
      